[2024-06-18T14:12:33.111+0545] {processor.py:161} INFO - Started process (PID=5056) to work on /root/apache_env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-06-18T14:12:33.112+0545] {processor.py:830} INFO - Processing file /root/apache_env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-06-18T14:12:33.113+0545] {logging_mixin.py:188} INFO - [2024-06-18T14:12:33.113+0545] {dagbag.py:545} INFO - Filling up the DagBag from /root/apache_env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-06-18T14:12:33.115+0545] {logging_mixin.py:188} INFO - [2024-06-18T14:12:33.115+0545] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/root/apache_env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-06-18T14:12:33.115+0545] {logging_mixin.py:188} INFO - [2024-06-18T14:12:33.115+0545] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-06-18T14:12:33.115+0545] {processor.py:842} WARNING - No viable dags retrieved from /root/apache_env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-06-18T14:12:33.123+0545] {processor.py:183} INFO - Processing /root/apache_env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.015 seconds
[2024-06-18T14:14:46.324+0545] {processor.py:161} INFO - Started process (PID=5360) to work on /root/apache_env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-06-18T14:14:46.325+0545] {processor.py:830} INFO - Processing file /root/apache_env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-06-18T14:14:46.326+0545] {logging_mixin.py:188} INFO - [2024-06-18T14:14:46.326+0545] {dagbag.py:545} INFO - Filling up the DagBag from /root/apache_env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-06-18T14:14:46.328+0545] {logging_mixin.py:188} INFO - [2024-06-18T14:14:46.328+0545] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/root/apache_env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-06-18T14:14:46.329+0545] {logging_mixin.py:188} INFO - [2024-06-18T14:14:46.329+0545] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-06-18T14:14:46.329+0545] {processor.py:842} WARNING - No viable dags retrieved from /root/apache_env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-06-18T14:14:46.336+0545] {processor.py:183} INFO - Processing /root/apache_env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.017 seconds
[2024-06-18T14:16:09.233+0545] {processor.py:161} INFO - Started process (PID=5586) to work on /root/apache_env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-06-18T14:16:09.234+0545] {processor.py:830} INFO - Processing file /root/apache_env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-06-18T14:16:09.235+0545] {logging_mixin.py:188} INFO - [2024-06-18T14:16:09.235+0545] {dagbag.py:545} INFO - Filling up the DagBag from /root/apache_env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-06-18T14:16:09.237+0545] {logging_mixin.py:188} INFO - [2024-06-18T14:16:09.237+0545] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/root/apache_env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-06-18T14:16:09.238+0545] {logging_mixin.py:188} INFO - [2024-06-18T14:16:09.237+0545] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-06-18T14:16:09.238+0545] {processor.py:842} WARNING - No viable dags retrieved from /root/apache_env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-06-18T14:16:09.244+0545] {processor.py:183} INFO - Processing /root/apache_env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.015 seconds
[2024-06-18T14:17:03.821+0545] {processor.py:161} INFO - Started process (PID=5723) to work on /root/apache_env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-06-18T14:17:03.823+0545] {processor.py:830} INFO - Processing file /root/apache_env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-06-18T14:17:03.824+0545] {logging_mixin.py:188} INFO - [2024-06-18T14:17:03.824+0545] {dagbag.py:545} INFO - Filling up the DagBag from /root/apache_env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-06-18T14:17:03.826+0545] {logging_mixin.py:188} INFO - [2024-06-18T14:17:03.826+0545] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/root/apache_env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-06-18T14:17:03.826+0545] {logging_mixin.py:188} INFO - [2024-06-18T14:17:03.826+0545] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-06-18T14:17:03.826+0545] {processor.py:842} WARNING - No viable dags retrieved from /root/apache_env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-06-18T14:17:03.833+0545] {processor.py:183} INFO - Processing /root/apache_env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.015 seconds
[2024-06-18T14:17:53.327+0545] {processor.py:161} INFO - Started process (PID=5846) to work on /root/apache_env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-06-18T14:17:53.328+0545] {processor.py:830} INFO - Processing file /root/apache_env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-06-18T14:17:53.329+0545] {logging_mixin.py:188} INFO - [2024-06-18T14:17:53.329+0545] {dagbag.py:545} INFO - Filling up the DagBag from /root/apache_env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-06-18T14:17:53.331+0545] {logging_mixin.py:188} INFO - [2024-06-18T14:17:53.331+0545] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/root/apache_env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-06-18T14:17:53.332+0545] {logging_mixin.py:188} INFO - [2024-06-18T14:17:53.332+0545] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-06-18T14:17:53.332+0545] {processor.py:842} WARNING - No viable dags retrieved from /root/apache_env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-06-18T14:17:53.339+0545] {processor.py:183} INFO - Processing /root/apache_env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.017 seconds
[2024-06-18T14:18:42.326+0545] {processor.py:161} INFO - Started process (PID=5923) to work on /root/apache_env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-06-18T14:18:42.327+0545] {processor.py:830} INFO - Processing file /root/apache_env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-06-18T14:18:42.328+0545] {logging_mixin.py:188} INFO - [2024-06-18T14:18:42.328+0545] {dagbag.py:545} INFO - Filling up the DagBag from /root/apache_env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-06-18T14:18:42.331+0545] {logging_mixin.py:188} INFO - [2024-06-18T14:18:42.330+0545] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/root/apache_env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-06-18T14:18:42.331+0545] {logging_mixin.py:188} INFO - [2024-06-18T14:18:42.331+0545] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-06-18T14:18:42.331+0545] {processor.py:842} WARNING - No viable dags retrieved from /root/apache_env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-06-18T14:18:42.338+0545] {processor.py:183} INFO - Processing /root/apache_env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.017 seconds
[2024-06-18T14:22:18.096+0545] {processor.py:161} INFO - Started process (PID=6533) to work on /root/apache_env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-06-18T14:22:18.097+0545] {processor.py:830} INFO - Processing file /root/apache_env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-06-18T14:22:18.098+0545] {logging_mixin.py:188} INFO - [2024-06-18T14:22:18.098+0545] {dagbag.py:545} INFO - Filling up the DagBag from /root/apache_env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-06-18T14:22:18.101+0545] {logging_mixin.py:188} INFO - [2024-06-18T14:22:18.100+0545] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/root/apache_env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-06-18T14:22:18.101+0545] {logging_mixin.py:188} INFO - [2024-06-18T14:22:18.101+0545] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-06-18T14:22:18.101+0545] {processor.py:842} WARNING - No viable dags retrieved from /root/apache_env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-06-18T14:22:18.107+0545] {processor.py:183} INFO - Processing /root/apache_env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.016 seconds
[2024-06-18T14:23:25.312+0545] {processor.py:161} INFO - Started process (PID=6749) to work on /root/apache_env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-06-18T14:23:25.314+0545] {processor.py:830} INFO - Processing file /root/apache_env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-06-18T14:23:25.315+0545] {logging_mixin.py:188} INFO - [2024-06-18T14:23:25.315+0545] {dagbag.py:545} INFO - Filling up the DagBag from /root/apache_env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-06-18T14:23:25.317+0545] {logging_mixin.py:188} INFO - [2024-06-18T14:23:25.317+0545] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/root/apache_env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-06-18T14:23:25.317+0545] {logging_mixin.py:188} INFO - [2024-06-18T14:23:25.317+0545] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-06-18T14:23:25.318+0545] {processor.py:842} WARNING - No viable dags retrieved from /root/apache_env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-06-18T14:23:25.324+0545] {processor.py:183} INFO - Processing /root/apache_env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.015 seconds
[2024-06-18T14:24:19.331+0545] {processor.py:161} INFO - Started process (PID=6881) to work on /root/apache_env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-06-18T14:24:19.332+0545] {processor.py:830} INFO - Processing file /root/apache_env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-06-18T14:24:19.333+0545] {logging_mixin.py:188} INFO - [2024-06-18T14:24:19.333+0545] {dagbag.py:545} INFO - Filling up the DagBag from /root/apache_env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-06-18T14:24:19.335+0545] {logging_mixin.py:188} INFO - [2024-06-18T14:24:19.335+0545] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/root/apache_env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-06-18T14:24:19.335+0545] {logging_mixin.py:188} INFO - [2024-06-18T14:24:19.335+0545] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-06-18T14:24:19.336+0545] {processor.py:842} WARNING - No viable dags retrieved from /root/apache_env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-06-18T14:24:19.342+0545] {processor.py:183} INFO - Processing /root/apache_env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.015 seconds
[2024-06-18T14:25:15.191+0545] {processor.py:161} INFO - Started process (PID=7045) to work on /root/apache_env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-06-18T14:25:15.193+0545] {processor.py:830} INFO - Processing file /root/apache_env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-06-18T14:25:15.195+0545] {logging_mixin.py:188} INFO - [2024-06-18T14:25:15.194+0545] {dagbag.py:545} INFO - Filling up the DagBag from /root/apache_env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-06-18T14:25:15.199+0545] {logging_mixin.py:188} INFO - [2024-06-18T14:25:15.198+0545] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/root/apache_env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-06-18T14:25:15.199+0545] {logging_mixin.py:188} INFO - [2024-06-18T14:25:15.199+0545] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-06-18T14:25:15.200+0545] {processor.py:842} WARNING - No viable dags retrieved from /root/apache_env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-06-18T14:25:15.211+0545] {processor.py:183} INFO - Processing /root/apache_env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.027 seconds
[2024-06-18T14:27:21.836+0545] {processor.py:161} INFO - Started process (PID=7384) to work on /root/apache_env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-06-18T14:27:21.838+0545] {processor.py:830} INFO - Processing file /root/apache_env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-06-18T14:27:21.839+0545] {logging_mixin.py:188} INFO - [2024-06-18T14:27:21.839+0545] {dagbag.py:545} INFO - Filling up the DagBag from /root/apache_env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-06-18T14:27:21.841+0545] {logging_mixin.py:188} INFO - [2024-06-18T14:27:21.841+0545] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/root/apache_env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-06-18T14:27:21.841+0545] {logging_mixin.py:188} INFO - [2024-06-18T14:27:21.841+0545] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-06-18T14:27:21.841+0545] {processor.py:842} WARNING - No viable dags retrieved from /root/apache_env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-06-18T14:27:21.848+0545] {processor.py:183} INFO - Processing /root/apache_env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.015 seconds
[2024-06-18T14:28:17.719+0545] {processor.py:161} INFO - Started process (PID=7534) to work on /root/apache_env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-06-18T14:28:17.720+0545] {processor.py:830} INFO - Processing file /root/apache_env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-06-18T14:28:17.721+0545] {logging_mixin.py:188} INFO - [2024-06-18T14:28:17.721+0545] {dagbag.py:545} INFO - Filling up the DagBag from /root/apache_env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-06-18T14:28:17.723+0545] {logging_mixin.py:188} INFO - [2024-06-18T14:28:17.723+0545] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/root/apache_env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-06-18T14:28:17.724+0545] {logging_mixin.py:188} INFO - [2024-06-18T14:28:17.724+0545] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-06-18T14:28:17.724+0545] {processor.py:842} WARNING - No viable dags retrieved from /root/apache_env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-06-18T14:28:17.732+0545] {processor.py:183} INFO - Processing /root/apache_env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.018 seconds
[2024-06-18T14:30:00.925+0545] {processor.py:161} INFO - Started process (PID=7789) to work on /root/apache_env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-06-18T14:30:00.927+0545] {processor.py:830} INFO - Processing file /root/apache_env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-06-18T14:30:00.928+0545] {logging_mixin.py:188} INFO - [2024-06-18T14:30:00.928+0545] {dagbag.py:545} INFO - Filling up the DagBag from /root/apache_env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-06-18T14:30:00.930+0545] {logging_mixin.py:188} INFO - [2024-06-18T14:30:00.930+0545] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/root/apache_env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-06-18T14:30:00.930+0545] {logging_mixin.py:188} INFO - [2024-06-18T14:30:00.930+0545] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-06-18T14:30:00.930+0545] {processor.py:842} WARNING - No viable dags retrieved from /root/apache_env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-06-18T14:30:00.936+0545] {processor.py:183} INFO - Processing /root/apache_env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.014 seconds
[2024-06-18T14:30:55.784+0545] {processor.py:161} INFO - Started process (PID=7927) to work on /root/apache_env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-06-18T14:30:55.786+0545] {processor.py:830} INFO - Processing file /root/apache_env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-06-18T14:30:55.787+0545] {logging_mixin.py:188} INFO - [2024-06-18T14:30:55.787+0545] {dagbag.py:545} INFO - Filling up the DagBag from /root/apache_env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-06-18T14:30:55.789+0545] {logging_mixin.py:188} INFO - [2024-06-18T14:30:55.789+0545] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/root/apache_env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-06-18T14:30:55.789+0545] {logging_mixin.py:188} INFO - [2024-06-18T14:30:55.789+0545] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-06-18T14:30:55.790+0545] {processor.py:842} WARNING - No viable dags retrieved from /root/apache_env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-06-18T14:30:55.796+0545] {processor.py:183} INFO - Processing /root/apache_env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.015 seconds
[2024-06-18T14:31:45.382+0545] {processor.py:161} INFO - Started process (PID=8049) to work on /root/apache_env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-06-18T14:31:45.384+0545] {processor.py:830} INFO - Processing file /root/apache_env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-06-18T14:31:45.385+0545] {logging_mixin.py:188} INFO - [2024-06-18T14:31:45.385+0545] {dagbag.py:545} INFO - Filling up the DagBag from /root/apache_env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-06-18T14:31:45.387+0545] {logging_mixin.py:188} INFO - [2024-06-18T14:31:45.387+0545] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/root/apache_env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-06-18T14:31:45.387+0545] {logging_mixin.py:188} INFO - [2024-06-18T14:31:45.387+0545] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-06-18T14:31:45.387+0545] {processor.py:842} WARNING - No viable dags retrieved from /root/apache_env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-06-18T14:31:45.394+0545] {processor.py:183} INFO - Processing /root/apache_env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.015 seconds
[2024-06-18T14:32:34.318+0545] {processor.py:161} INFO - Started process (PID=8170) to work on /root/apache_env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-06-18T14:32:34.319+0545] {processor.py:830} INFO - Processing file /root/apache_env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-06-18T14:32:34.320+0545] {logging_mixin.py:188} INFO - [2024-06-18T14:32:34.320+0545] {dagbag.py:545} INFO - Filling up the DagBag from /root/apache_env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-06-18T14:32:34.322+0545] {logging_mixin.py:188} INFO - [2024-06-18T14:32:34.322+0545] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/root/apache_env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-06-18T14:32:34.322+0545] {logging_mixin.py:188} INFO - [2024-06-18T14:32:34.322+0545] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-06-18T14:32:34.322+0545] {processor.py:842} WARNING - No viable dags retrieved from /root/apache_env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-06-18T14:32:34.329+0545] {processor.py:183} INFO - Processing /root/apache_env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.015 seconds
[2024-06-18T14:33:26.747+0545] {processor.py:161} INFO - Started process (PID=8299) to work on /root/apache_env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-06-18T14:33:26.749+0545] {processor.py:830} INFO - Processing file /root/apache_env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-06-18T14:33:26.750+0545] {logging_mixin.py:188} INFO - [2024-06-18T14:33:26.750+0545] {dagbag.py:545} INFO - Filling up the DagBag from /root/apache_env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-06-18T14:33:26.752+0545] {logging_mixin.py:188} INFO - [2024-06-18T14:33:26.751+0545] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/root/apache_env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-06-18T14:33:26.752+0545] {logging_mixin.py:188} INFO - [2024-06-18T14:33:26.752+0545] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-06-18T14:33:26.753+0545] {processor.py:842} WARNING - No viable dags retrieved from /root/apache_env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-06-18T14:33:26.759+0545] {processor.py:183} INFO - Processing /root/apache_env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.016 seconds
[2024-06-18T14:34:12.906+0545] {processor.py:161} INFO - Started process (PID=8418) to work on /root/apache_env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-06-18T14:34:12.907+0545] {processor.py:830} INFO - Processing file /root/apache_env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-06-18T14:34:12.909+0545] {logging_mixin.py:188} INFO - [2024-06-18T14:34:12.908+0545] {dagbag.py:545} INFO - Filling up the DagBag from /root/apache_env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-06-18T14:34:12.911+0545] {logging_mixin.py:188} INFO - [2024-06-18T14:34:12.911+0545] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/root/apache_env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-06-18T14:34:12.911+0545] {logging_mixin.py:188} INFO - [2024-06-18T14:34:12.911+0545] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-06-18T14:34:12.911+0545] {processor.py:842} WARNING - No viable dags retrieved from /root/apache_env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-06-18T14:34:12.918+0545] {processor.py:183} INFO - Processing /root/apache_env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.015 seconds
[2024-06-18T14:34:56.251+0545] {processor.py:161} INFO - Started process (PID=8528) to work on /root/apache_env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-06-18T14:34:56.252+0545] {processor.py:830} INFO - Processing file /root/apache_env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-06-18T14:34:56.254+0545] {logging_mixin.py:188} INFO - [2024-06-18T14:34:56.253+0545] {dagbag.py:545} INFO - Filling up the DagBag from /root/apache_env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-06-18T14:34:56.255+0545] {logging_mixin.py:188} INFO - [2024-06-18T14:34:56.255+0545] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/root/apache_env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-06-18T14:34:56.256+0545] {logging_mixin.py:188} INFO - [2024-06-18T14:34:56.256+0545] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-06-18T14:34:56.256+0545] {processor.py:842} WARNING - No viable dags retrieved from /root/apache_env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-06-18T14:34:56.262+0545] {processor.py:183} INFO - Processing /root/apache_env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.015 seconds
[2024-06-18T14:35:51.145+0545] {processor.py:161} INFO - Started process (PID=8697) to work on /root/apache_env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-06-18T14:35:51.147+0545] {processor.py:830} INFO - Processing file /root/apache_env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-06-18T14:35:51.148+0545] {logging_mixin.py:188} INFO - [2024-06-18T14:35:51.148+0545] {dagbag.py:545} INFO - Filling up the DagBag from /root/apache_env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-06-18T14:35:51.151+0545] {logging_mixin.py:188} INFO - [2024-06-18T14:35:51.150+0545] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/root/apache_env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-06-18T14:35:51.151+0545] {logging_mixin.py:188} INFO - [2024-06-18T14:35:51.151+0545] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-06-18T14:35:51.151+0545] {processor.py:842} WARNING - No viable dags retrieved from /root/apache_env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-06-18T14:35:51.159+0545] {processor.py:183} INFO - Processing /root/apache_env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.018 seconds
[2024-06-18T14:36:33.664+0545] {processor.py:161} INFO - Started process (PID=8803) to work on /root/apache_env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-06-18T14:36:33.666+0545] {processor.py:830} INFO - Processing file /root/apache_env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-06-18T14:36:33.667+0545] {logging_mixin.py:188} INFO - [2024-06-18T14:36:33.667+0545] {dagbag.py:545} INFO - Filling up the DagBag from /root/apache_env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-06-18T14:36:33.669+0545] {logging_mixin.py:188} INFO - [2024-06-18T14:36:33.669+0545] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/root/apache_env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-06-18T14:36:33.669+0545] {logging_mixin.py:188} INFO - [2024-06-18T14:36:33.669+0545] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-06-18T14:36:33.669+0545] {processor.py:842} WARNING - No viable dags retrieved from /root/apache_env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-06-18T14:36:33.676+0545] {processor.py:183} INFO - Processing /root/apache_env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.016 seconds
[2024-06-18T14:37:18.425+0545] {processor.py:161} INFO - Started process (PID=8912) to work on /root/apache_env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-06-18T14:37:18.426+0545] {processor.py:830} INFO - Processing file /root/apache_env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-06-18T14:37:18.427+0545] {logging_mixin.py:188} INFO - [2024-06-18T14:37:18.427+0545] {dagbag.py:545} INFO - Filling up the DagBag from /root/apache_env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-06-18T14:37:18.429+0545] {logging_mixin.py:188} INFO - [2024-06-18T14:37:18.428+0545] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/root/apache_env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-06-18T14:37:18.429+0545] {logging_mixin.py:188} INFO - [2024-06-18T14:37:18.429+0545] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-06-18T14:37:18.429+0545] {processor.py:842} WARNING - No viable dags retrieved from /root/apache_env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-06-18T14:37:18.435+0545] {processor.py:183} INFO - Processing /root/apache_env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.015 seconds
[2024-06-18T14:38:04.542+0545] {processor.py:161} INFO - Started process (PID=9029) to work on /root/apache_env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-06-18T14:38:04.543+0545] {processor.py:830} INFO - Processing file /root/apache_env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-06-18T14:38:04.545+0545] {logging_mixin.py:188} INFO - [2024-06-18T14:38:04.544+0545] {dagbag.py:545} INFO - Filling up the DagBag from /root/apache_env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-06-18T14:38:04.546+0545] {logging_mixin.py:188} INFO - [2024-06-18T14:38:04.546+0545] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/root/apache_env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-06-18T14:38:04.547+0545] {logging_mixin.py:188} INFO - [2024-06-18T14:38:04.547+0545] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-06-18T14:38:04.547+0545] {processor.py:842} WARNING - No viable dags retrieved from /root/apache_env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-06-18T14:38:04.553+0545] {processor.py:183} INFO - Processing /root/apache_env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.015 seconds
[2024-06-18T14:38:50.725+0545] {processor.py:161} INFO - Started process (PID=9145) to work on /root/apache_env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-06-18T14:38:50.726+0545] {processor.py:830} INFO - Processing file /root/apache_env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-06-18T14:38:50.727+0545] {logging_mixin.py:188} INFO - [2024-06-18T14:38:50.727+0545] {dagbag.py:545} INFO - Filling up the DagBag from /root/apache_env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-06-18T14:38:50.729+0545] {logging_mixin.py:188} INFO - [2024-06-18T14:38:50.729+0545] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/root/apache_env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-06-18T14:38:50.729+0545] {logging_mixin.py:188} INFO - [2024-06-18T14:38:50.729+0545] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-06-18T14:38:50.729+0545] {processor.py:842} WARNING - No viable dags retrieved from /root/apache_env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-06-18T14:38:50.736+0545] {processor.py:183} INFO - Processing /root/apache_env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.015 seconds
[2024-06-18T14:39:38.064+0545] {processor.py:161} INFO - Started process (PID=9265) to work on /root/apache_env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-06-18T14:39:38.066+0545] {processor.py:830} INFO - Processing file /root/apache_env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-06-18T14:39:38.067+0545] {logging_mixin.py:188} INFO - [2024-06-18T14:39:38.067+0545] {dagbag.py:545} INFO - Filling up the DagBag from /root/apache_env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-06-18T14:39:38.069+0545] {logging_mixin.py:188} INFO - [2024-06-18T14:39:38.069+0545] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/root/apache_env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-06-18T14:39:38.069+0545] {logging_mixin.py:188} INFO - [2024-06-18T14:39:38.069+0545] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-06-18T14:39:38.069+0545] {processor.py:842} WARNING - No viable dags retrieved from /root/apache_env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-06-18T14:39:38.076+0545] {processor.py:183} INFO - Processing /root/apache_env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.016 seconds
[2024-06-18T14:40:23.818+0545] {processor.py:161} INFO - Started process (PID=9380) to work on /root/apache_env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-06-18T14:40:23.819+0545] {processor.py:830} INFO - Processing file /root/apache_env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-06-18T14:40:23.820+0545] {logging_mixin.py:188} INFO - [2024-06-18T14:40:23.820+0545] {dagbag.py:545} INFO - Filling up the DagBag from /root/apache_env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-06-18T14:40:23.822+0545] {logging_mixin.py:188} INFO - [2024-06-18T14:40:23.822+0545] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/root/apache_env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-06-18T14:40:23.823+0545] {logging_mixin.py:188} INFO - [2024-06-18T14:40:23.823+0545] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-06-18T14:40:23.823+0545] {processor.py:842} WARNING - No viable dags retrieved from /root/apache_env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-06-18T14:40:23.830+0545] {processor.py:183} INFO - Processing /root/apache_env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.017 seconds
[2024-06-18T14:41:10.489+0545] {processor.py:161} INFO - Started process (PID=9498) to work on /root/apache_env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-06-18T14:41:10.491+0545] {processor.py:830} INFO - Processing file /root/apache_env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-06-18T14:41:10.492+0545] {logging_mixin.py:188} INFO - [2024-06-18T14:41:10.492+0545] {dagbag.py:545} INFO - Filling up the DagBag from /root/apache_env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-06-18T14:41:10.494+0545] {logging_mixin.py:188} INFO - [2024-06-18T14:41:10.494+0545] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/root/apache_env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-06-18T14:41:10.494+0545] {logging_mixin.py:188} INFO - [2024-06-18T14:41:10.494+0545] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-06-18T14:41:10.495+0545] {processor.py:842} WARNING - No viable dags retrieved from /root/apache_env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-06-18T14:41:10.501+0545] {processor.py:183} INFO - Processing /root/apache_env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.015 seconds
[2024-06-18T14:41:54.976+0545] {processor.py:161} INFO - Started process (PID=9611) to work on /root/apache_env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-06-18T14:41:54.978+0545] {processor.py:830} INFO - Processing file /root/apache_env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-06-18T14:41:54.979+0545] {logging_mixin.py:188} INFO - [2024-06-18T14:41:54.979+0545] {dagbag.py:545} INFO - Filling up the DagBag from /root/apache_env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-06-18T14:41:54.981+0545] {logging_mixin.py:188} INFO - [2024-06-18T14:41:54.981+0545] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/root/apache_env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-06-18T14:41:54.981+0545] {logging_mixin.py:188} INFO - [2024-06-18T14:41:54.981+0545] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-06-18T14:41:54.981+0545] {processor.py:842} WARNING - No viable dags retrieved from /root/apache_env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-06-18T14:41:54.988+0545] {processor.py:183} INFO - Processing /root/apache_env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.016 seconds
[2024-06-18T14:42:37.732+0545] {processor.py:161} INFO - Started process (PID=9715) to work on /root/apache_env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-06-18T14:42:37.733+0545] {processor.py:830} INFO - Processing file /root/apache_env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-06-18T14:42:37.734+0545] {logging_mixin.py:188} INFO - [2024-06-18T14:42:37.734+0545] {dagbag.py:545} INFO - Filling up the DagBag from /root/apache_env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-06-18T14:42:37.736+0545] {logging_mixin.py:188} INFO - [2024-06-18T14:42:37.736+0545] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/root/apache_env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-06-18T14:42:37.736+0545] {logging_mixin.py:188} INFO - [2024-06-18T14:42:37.736+0545] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-06-18T14:42:37.737+0545] {processor.py:842} WARNING - No viable dags retrieved from /root/apache_env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-06-18T14:42:37.743+0545] {processor.py:183} INFO - Processing /root/apache_env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.015 seconds
[2024-06-18T14:43:21.715+0545] {processor.py:161} INFO - Started process (PID=9827) to work on /root/apache_env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-06-18T14:43:21.716+0545] {processor.py:830} INFO - Processing file /root/apache_env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-06-18T14:43:21.718+0545] {logging_mixin.py:188} INFO - [2024-06-18T14:43:21.717+0545] {dagbag.py:545} INFO - Filling up the DagBag from /root/apache_env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-06-18T14:43:21.720+0545] {logging_mixin.py:188} INFO - [2024-06-18T14:43:21.720+0545] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/root/apache_env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-06-18T14:43:21.720+0545] {logging_mixin.py:188} INFO - [2024-06-18T14:43:21.720+0545] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-06-18T14:43:21.720+0545] {processor.py:842} WARNING - No viable dags retrieved from /root/apache_env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-06-18T14:43:21.727+0545] {processor.py:183} INFO - Processing /root/apache_env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.016 seconds
[2024-06-18T14:44:09.033+0545] {processor.py:161} INFO - Started process (PID=9944) to work on /root/apache_env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-06-18T14:44:09.034+0545] {processor.py:830} INFO - Processing file /root/apache_env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-06-18T14:44:09.036+0545] {logging_mixin.py:188} INFO - [2024-06-18T14:44:09.035+0545] {dagbag.py:545} INFO - Filling up the DagBag from /root/apache_env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-06-18T14:44:09.038+0545] {logging_mixin.py:188} INFO - [2024-06-18T14:44:09.037+0545] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/root/apache_env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-06-18T14:44:09.038+0545] {logging_mixin.py:188} INFO - [2024-06-18T14:44:09.038+0545] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-06-18T14:44:09.038+0545] {processor.py:842} WARNING - No viable dags retrieved from /root/apache_env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-06-18T14:44:09.044+0545] {processor.py:183} INFO - Processing /root/apache_env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.017 seconds
[2024-06-18T14:44:53.478+0545] {processor.py:161} INFO - Started process (PID=10057) to work on /root/apache_env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-06-18T14:44:53.479+0545] {processor.py:830} INFO - Processing file /root/apache_env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-06-18T14:44:53.481+0545] {logging_mixin.py:188} INFO - [2024-06-18T14:44:53.480+0545] {dagbag.py:545} INFO - Filling up the DagBag from /root/apache_env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-06-18T14:44:53.483+0545] {logging_mixin.py:188} INFO - [2024-06-18T14:44:53.482+0545] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/root/apache_env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-06-18T14:44:53.483+0545] {logging_mixin.py:188} INFO - [2024-06-18T14:44:53.483+0545] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-06-18T14:44:53.483+0545] {processor.py:842} WARNING - No viable dags retrieved from /root/apache_env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-06-18T14:44:53.489+0545] {processor.py:183} INFO - Processing /root/apache_env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.015 seconds
[2024-06-18T14:45:50.700+0545] {processor.py:161} INFO - Started process (PID=10227) to work on /root/apache_env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-06-18T14:45:50.701+0545] {processor.py:830} INFO - Processing file /root/apache_env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-06-18T14:45:50.702+0545] {logging_mixin.py:188} INFO - [2024-06-18T14:45:50.702+0545] {dagbag.py:545} INFO - Filling up the DagBag from /root/apache_env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-06-18T14:45:50.704+0545] {logging_mixin.py:188} INFO - [2024-06-18T14:45:50.704+0545] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/root/apache_env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-06-18T14:45:50.704+0545] {logging_mixin.py:188} INFO - [2024-06-18T14:45:50.704+0545] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-06-18T14:45:50.705+0545] {processor.py:842} WARNING - No viable dags retrieved from /root/apache_env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-06-18T14:45:50.711+0545] {processor.py:183} INFO - Processing /root/apache_env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.016 seconds
[2024-06-18T14:46:33.473+0545] {processor.py:161} INFO - Started process (PID=10334) to work on /root/apache_env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-06-18T14:46:33.474+0545] {processor.py:830} INFO - Processing file /root/apache_env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-06-18T14:46:33.475+0545] {logging_mixin.py:188} INFO - [2024-06-18T14:46:33.475+0545] {dagbag.py:545} INFO - Filling up the DagBag from /root/apache_env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-06-18T14:46:33.478+0545] {logging_mixin.py:188} INFO - [2024-06-18T14:46:33.477+0545] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/root/apache_env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-06-18T14:46:33.478+0545] {logging_mixin.py:188} INFO - [2024-06-18T14:46:33.478+0545] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-06-18T14:46:33.478+0545] {processor.py:842} WARNING - No viable dags retrieved from /root/apache_env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-06-18T14:46:33.486+0545] {processor.py:183} INFO - Processing /root/apache_env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.018 seconds
[2024-06-18T14:47:16.820+0545] {processor.py:161} INFO - Started process (PID=10446) to work on /root/apache_env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-06-18T14:47:16.821+0545] {processor.py:830} INFO - Processing file /root/apache_env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-06-18T14:47:16.823+0545] {logging_mixin.py:188} INFO - [2024-06-18T14:47:16.822+0545] {dagbag.py:545} INFO - Filling up the DagBag from /root/apache_env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-06-18T14:47:16.824+0545] {logging_mixin.py:188} INFO - [2024-06-18T14:47:16.824+0545] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/root/apache_env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-06-18T14:47:16.825+0545] {logging_mixin.py:188} INFO - [2024-06-18T14:47:16.825+0545] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-06-18T14:47:16.825+0545] {processor.py:842} WARNING - No viable dags retrieved from /root/apache_env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-06-18T14:47:16.831+0545] {processor.py:183} INFO - Processing /root/apache_env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.015 seconds
[2024-06-18T14:48:00.770+0545] {processor.py:161} INFO - Started process (PID=10554) to work on /root/apache_env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-06-18T14:48:00.772+0545] {processor.py:830} INFO - Processing file /root/apache_env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-06-18T14:48:00.773+0545] {logging_mixin.py:188} INFO - [2024-06-18T14:48:00.772+0545] {dagbag.py:545} INFO - Filling up the DagBag from /root/apache_env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-06-18T14:48:00.775+0545] {logging_mixin.py:188} INFO - [2024-06-18T14:48:00.774+0545] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/root/apache_env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-06-18T14:48:00.775+0545] {logging_mixin.py:188} INFO - [2024-06-18T14:48:00.775+0545] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-06-18T14:48:00.775+0545] {processor.py:842} WARNING - No viable dags retrieved from /root/apache_env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-06-18T14:48:00.781+0545] {processor.py:183} INFO - Processing /root/apache_env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.015 seconds
[2024-06-18T14:48:45.108+0545] {processor.py:161} INFO - Started process (PID=10667) to work on /root/apache_env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-06-18T14:48:45.109+0545] {processor.py:830} INFO - Processing file /root/apache_env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-06-18T14:48:45.110+0545] {logging_mixin.py:188} INFO - [2024-06-18T14:48:45.110+0545] {dagbag.py:545} INFO - Filling up the DagBag from /root/apache_env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-06-18T14:48:45.112+0545] {logging_mixin.py:188} INFO - [2024-06-18T14:48:45.112+0545] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/root/apache_env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-06-18T14:48:45.112+0545] {logging_mixin.py:188} INFO - [2024-06-18T14:48:45.112+0545] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-06-18T14:48:45.112+0545] {processor.py:842} WARNING - No viable dags retrieved from /root/apache_env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-06-18T14:48:45.119+0545] {processor.py:183} INFO - Processing /root/apache_env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.015 seconds
[2024-06-18T14:49:32.897+0545] {processor.py:161} INFO - Started process (PID=10788) to work on /root/apache_env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-06-18T14:49:32.898+0545] {processor.py:830} INFO - Processing file /root/apache_env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-06-18T14:49:32.899+0545] {logging_mixin.py:188} INFO - [2024-06-18T14:49:32.899+0545] {dagbag.py:545} INFO - Filling up the DagBag from /root/apache_env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-06-18T14:49:32.901+0545] {logging_mixin.py:188} INFO - [2024-06-18T14:49:32.901+0545] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/root/apache_env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-06-18T14:49:32.901+0545] {logging_mixin.py:188} INFO - [2024-06-18T14:49:32.901+0545] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-06-18T14:49:32.902+0545] {processor.py:842} WARNING - No viable dags retrieved from /root/apache_env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-06-18T14:49:32.908+0545] {processor.py:183} INFO - Processing /root/apache_env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.015 seconds
[2024-06-18T14:50:15.057+0545] {processor.py:161} INFO - Started process (PID=10896) to work on /root/apache_env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-06-18T14:50:15.058+0545] {processor.py:830} INFO - Processing file /root/apache_env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-06-18T14:50:15.059+0545] {logging_mixin.py:188} INFO - [2024-06-18T14:50:15.059+0545] {dagbag.py:545} INFO - Filling up the DagBag from /root/apache_env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-06-18T14:50:15.061+0545] {logging_mixin.py:188} INFO - [2024-06-18T14:50:15.061+0545] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/root/apache_env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-06-18T14:50:15.062+0545] {logging_mixin.py:188} INFO - [2024-06-18T14:50:15.061+0545] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-06-18T14:50:15.062+0545] {processor.py:842} WARNING - No viable dags retrieved from /root/apache_env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-06-18T14:50:15.069+0545] {processor.py:183} INFO - Processing /root/apache_env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.016 seconds
[2024-06-18T14:51:00.633+0545] {processor.py:161} INFO - Started process (PID=11012) to work on /root/apache_env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-06-18T14:51:00.635+0545] {processor.py:830} INFO - Processing file /root/apache_env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-06-18T14:51:00.636+0545] {logging_mixin.py:188} INFO - [2024-06-18T14:51:00.636+0545] {dagbag.py:545} INFO - Filling up the DagBag from /root/apache_env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-06-18T14:51:00.638+0545] {logging_mixin.py:188} INFO - [2024-06-18T14:51:00.638+0545] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/root/apache_env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-06-18T14:51:00.638+0545] {logging_mixin.py:188} INFO - [2024-06-18T14:51:00.638+0545] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-06-18T14:51:00.639+0545] {processor.py:842} WARNING - No viable dags retrieved from /root/apache_env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-06-18T14:51:00.646+0545] {processor.py:183} INFO - Processing /root/apache_env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.017 seconds
[2024-06-18T14:51:44.008+0545] {processor.py:161} INFO - Started process (PID=11120) to work on /root/apache_env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-06-18T14:51:44.009+0545] {processor.py:830} INFO - Processing file /root/apache_env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-06-18T14:51:44.010+0545] {logging_mixin.py:188} INFO - [2024-06-18T14:51:44.010+0545] {dagbag.py:545} INFO - Filling up the DagBag from /root/apache_env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-06-18T14:51:44.012+0545] {logging_mixin.py:188} INFO - [2024-06-18T14:51:44.012+0545] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/root/apache_env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-06-18T14:51:44.013+0545] {logging_mixin.py:188} INFO - [2024-06-18T14:51:44.013+0545] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-06-18T14:51:44.013+0545] {processor.py:842} WARNING - No viable dags retrieved from /root/apache_env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-06-18T14:51:44.020+0545] {processor.py:183} INFO - Processing /root/apache_env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.016 seconds
