[2024-06-18T14:15:56.343+0545] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-18T14:15:56.354+0545] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Backup_Database.backup_task scheduled__2024-06-18T08:20:00+00:00 [queued]>
[2024-06-18T14:15:56.358+0545] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Backup_Database.backup_task scheduled__2024-06-18T08:20:00+00:00 [queued]>
[2024-06-18T14:15:56.358+0545] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-06-18T14:15:56.369+0545] {taskinstance.py:2330} INFO - Executing <Task(BashOperator): backup_task> on 2024-06-18 08:20:00+00:00
[2024-06-18T14:15:56.371+0545] {standard_task_runner.py:63} INFO - Started process 5541 to run task
[2024-06-18T14:15:56.374+0545] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'Backup_Database', 'backup_task', 'scheduled__2024-06-18T08:20:00+00:00', '--job-id', '6', '--raw', '--subdir', 'DAGS_FOLDER/backup.py', '--cfg-path', '/tmp/tmplp1o6ss9']
[2024-06-18T14:15:56.374+0545] {standard_task_runner.py:91} INFO - Job 6: Subtask backup_task
[2024-06-18T14:15:56.405+0545] {task_command.py:426} INFO - Running <TaskInstance: Backup_Database.backup_task scheduled__2024-06-18T08:20:00+00:00 [running]> on host Heathen.
[2024-06-18T14:15:56.448+0545] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='avyu' AIRFLOW_CTX_DAG_ID='Backup_Database' AIRFLOW_CTX_TASK_ID='backup_task' AIRFLOW_CTX_EXECUTION_DATE='2024-06-18T08:20:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-06-18T08:20:00+00:00'
[2024-06-18T14:15:56.449+0545] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-18T14:15:56.449+0545] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-06-18T14:15:56.450+0545] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', '/root/airflow/bashScripts/backup.sh ']
[2024-06-18T14:15:56.454+0545] {subprocess.py:86} INFO - Output:
[2024-06-18T14:15:56.463+0545] {subprocess.py:93} INFO - mysql: [Warning] Using a password on the command line interface can be insecure.
[2024-06-18T14:15:56.543+0545] {subprocess.py:93} INFO - /root/airflow/bashScripts/backup.sh: line 20: bc: command not found
[2024-06-18T14:15:56.607+0545] {subprocess.py:93} INFO - /root/airflow/bashScripts/backup.sh: line 27: bc: command not found
[2024-06-18T14:15:56.666+0545] {subprocess.py:93} INFO - /root/airflow/bashScripts/backup.sh: line 30: bc: command not found
[2024-06-18T14:15:56.666+0545] {subprocess.py:93} INFO - /root/airflow/bashScripts/backup.sh: line 30: [: -eq: unary operator expected
[2024-06-18T14:15:56.666+0545] {subprocess.py:93} INFO - Backup Failed.|Required Space: GB, Available Space: GB
[2024-06-18T14:15:56.666+0545] {subprocess.py:97} INFO - Command exited with return code 0
[2024-06-18T14:15:56.667+0545] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-18T14:15:56.680+0545] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=Backup_Database, task_id=backup_task, run_id=scheduled__2024-06-18T08:20:00+00:00, execution_date=20240618T082000, start_date=20240618T083056, end_date=20240618T083056
[2024-06-18T14:15:56.706+0545] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-06-18T14:15:56.718+0545] {taskinstance.py:3503} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-06-18T14:15:56.723+0545] {local_task_job_runner.py:222} INFO - ::endgroup::
